### ISSUE TITLE
Feature request - ability to select media library items when uploading files/images

### ISSUE THREAD

**Issue by jude86-7** [pixelninja/media_library#1]
Hi this extension looks great. 
However do you have any plans to extend this so that files shown in the media library can be selected on an upload field within a section.
Do you think it would be possible for a user to upload an image using the upload field OR select an image from the media library that is already uploaded?
Many thanks

**Comment by pixelninja** [comment]
Yes that's definitely on my priority list for this extension.

The aim is to create a field that replaces the upload field, rather than extends it. This extension allows uploading so it's doubling up functionality. It would be a pretty simple field, with a button that opens the media library and the option to select a file which then adds the file path to a readonly input field.

I just need the time to get there!

**Comment by jude86-7** [comment]
That sounds brilliant! Thank you for taking the time to come back to me and let me know!

Much appreciated :)

**Comment by pixelninja** [comment]
@jude86-7 letting you know that I’ve just pushed an update with that new field included :)

**Comment by jude86-7** [comment]
@pixelninja Thank you, this looks great, I'll give it a go! :)
